version: '3'
services:


  db:
    image: mariadb
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql/data
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_example
      MYSQL_USER: springuser
      MYSQL_PASSWORD: apassword

  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080

  web:
    build: .
    depends_on:
      - db
    ports:
      - 8090:8090

volumes:
  mysql-data:



